-- Erlbrew Café Database Schema
-- Run this script to initialize the MySQL database.
-- Usage: mysql -h 192.168.75.101 -u root -p < server/init.sql

CREATE DATABASE IF NOT EXISTS erlbrew
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE erlbrew;

CREATE TABLE IF NOT EXISTS gallery_photos (
  slot INT UNSIGNED NOT NULL PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) DEFAULT NULL,
  mime_type VARCHAR(50) DEFAULT NULL,
  file_size INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS business_hours (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  day_label VARCHAR(100) NOT NULL,
  hours_text VARCHAR(100) NOT NULL DEFAULT '',
  is_highlighted TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO business_hours (id, day_label, hours_text, is_highlighted, sort_order) VALUES
(1, 'Monday – Friday', '7:00 AM – 8:00 PM', 0, 1),
(2, 'Saturday',       '7:00 AM – 9:00 PM', 0, 2),
(3, 'Sunday',         '8:00 AM – 7:00 PM', 0, 3),
(4, 'Holidays',       'Check our socials',  1, 4);

CREATE TABLE IF NOT EXISTS about_photo (
  id INT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  filename VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) DEFAULT NULL,
  mime_type VARCHAR(50) DEFAULT NULL,
  file_size INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_users (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS menu_categories (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  cat VARCHAR(100) NOT NULL,
  ja VARCHAR(100) NOT NULL DEFAULT '',
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS menu_items (
  id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  category_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  price INT UNSIGNED NOT NULL DEFAULT 0,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create a dedicated user with full DML + CREATE for auto-setup (change password in production)
CREATE USER IF NOT EXISTS 'erlbrew'@'%' IDENTIFIED BY 'erlbrew_prod_2026';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE ON erlbrew.* TO 'erlbrew'@'%';
FLUSH PRIVILEGES;
